# TCL File Generated by Component Editor 18.1
# Fri Nov 08 10:16:19 CET 2024
# DO NOT MODIFY


# 
# Gestion_verin "Gestion_verin" v1.0
#  2024.11.08.10:16:19
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Gestion_verin
# 
set_module_property DESCRIPTION ""
set_module_property NAME Gestion_verin
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Gestion_verin
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL top_system
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Gestion_ADC.vhd VHDL PATH Gestion_ADC.vhd
add_fileset_file Gestion_Avalon.vhd VHDL PATH Gestion_Avalon.vhd
add_fileset_file PWM.vhd VHDL PATH PWM.vhd
add_fileset_file controle_butees.vhd VHDL PATH controle_butees.vhd
add_fileset_file top_system.vhd VHDL PATH top_system.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 address address Input 3
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point Clk_adc
# 
add_interface Clk_adc conduit end
set_interface_property Clk_adc associatedClock clock
set_interface_property Clk_adc associatedReset reset
set_interface_property Clk_adc ENABLED true
set_interface_property Clk_adc EXPORT_OF ""
set_interface_property Clk_adc PORT_NAME_MAP ""
set_interface_property Clk_adc CMSIS_SVD_VARIABLES ""
set_interface_property Clk_adc SVD_ADDRESS_GROUP ""

add_interface_port Clk_adc Clk_adc writeresponsevalid_n Output 1


# 
# connection point Cs_n
# 
add_interface Cs_n conduit end
set_interface_property Cs_n associatedClock clock
set_interface_property Cs_n associatedReset reset
set_interface_property Cs_n ENABLED true
set_interface_property Cs_n EXPORT_OF ""
set_interface_property Cs_n PORT_NAME_MAP ""
set_interface_property Cs_n CMSIS_SVD_VARIABLES ""
set_interface_property Cs_n SVD_ADDRESS_GROUP ""

add_interface_port Cs_n Cs_n writeresponsevalid_n Output 1


# 
# connection point Data_in_adc
# 
add_interface Data_in_adc conduit end
set_interface_property Data_in_adc associatedClock clock
set_interface_property Data_in_adc associatedReset reset
set_interface_property Data_in_adc ENABLED true
set_interface_property Data_in_adc EXPORT_OF ""
set_interface_property Data_in_adc PORT_NAME_MAP ""
set_interface_property Data_in_adc CMSIS_SVD_VARIABLES ""
set_interface_property Data_in_adc SVD_ADDRESS_GROUP ""

add_interface_port Data_in_adc Data_in_adc beginbursttransfer Input 1


# 
# connection point sens_out
# 
add_interface sens_out conduit end
set_interface_property sens_out associatedClock clock
set_interface_property sens_out associatedReset reset
set_interface_property sens_out ENABLED true
set_interface_property sens_out EXPORT_OF ""
set_interface_property sens_out PORT_NAME_MAP ""
set_interface_property sens_out CMSIS_SVD_VARIABLES ""
set_interface_property sens_out SVD_ADDRESS_GROUP ""

add_interface_port sens_out sens_out writeresponsevalid_n Output 1


# 
# connection point pwm_out
# 
add_interface pwm_out conduit end
set_interface_property pwm_out associatedClock clock
set_interface_property pwm_out associatedReset reset
set_interface_property pwm_out ENABLED true
set_interface_property pwm_out EXPORT_OF ""
set_interface_property pwm_out PORT_NAME_MAP ""
set_interface_property pwm_out CMSIS_SVD_VARIABLES ""
set_interface_property pwm_out SVD_ADDRESS_GROUP ""

add_interface_port pwm_out pwm_out writeresponsevalid_n Output 1

