# TCL File Generated by Component Editor 18.1
# Fri Nov 08 10:43:53 CET 2024
# DO NOT MODIFY


# 
# gestion_bp "gestion_bp" v1.0
#  2024.11.08.10:43:53
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module gestion_bp
# 
set_module_property DESCRIPTION ""
set_module_property NAME gestion_bp
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME gestion_bp
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_gestion_bp
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_gestion_bp.vhd VHDL PATH avalon_gestion_bp.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 address address Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point out_bip
# 
add_interface out_bip conduit end
set_interface_property out_bip associatedClock clock
set_interface_property out_bip associatedReset ""
set_interface_property out_bip ENABLED true
set_interface_property out_bip EXPORT_OF ""
set_interface_property out_bip PORT_NAME_MAP ""
set_interface_property out_bip CMSIS_SVD_VARIABLES ""
set_interface_property out_bip SVD_ADDRESS_GROUP ""

add_interface_port out_bip out_bip writeresponsevalid_n Output 1


# 
# connection point BP_Babord
# 
add_interface BP_Babord conduit end
set_interface_property BP_Babord associatedClock clock
set_interface_property BP_Babord associatedReset ""
set_interface_property BP_Babord ENABLED true
set_interface_property BP_Babord EXPORT_OF ""
set_interface_property BP_Babord PORT_NAME_MAP ""
set_interface_property BP_Babord CMSIS_SVD_VARIABLES ""
set_interface_property BP_Babord SVD_ADDRESS_GROUP ""

add_interface_port BP_Babord BP_Babord beginbursttransfer Input 1


# 
# connection point BP_STBY
# 
add_interface BP_STBY conduit end
set_interface_property BP_STBY associatedClock clock
set_interface_property BP_STBY associatedReset ""
set_interface_property BP_STBY ENABLED true
set_interface_property BP_STBY EXPORT_OF ""
set_interface_property BP_STBY PORT_NAME_MAP ""
set_interface_property BP_STBY CMSIS_SVD_VARIABLES ""
set_interface_property BP_STBY SVD_ADDRESS_GROUP ""

add_interface_port BP_STBY BP_STBY beginbursttransfer Input 1


# 
# connection point BP_Tribord
# 
add_interface BP_Tribord conduit end
set_interface_property BP_Tribord associatedClock clock
set_interface_property BP_Tribord associatedReset ""
set_interface_property BP_Tribord ENABLED true
set_interface_property BP_Tribord EXPORT_OF ""
set_interface_property BP_Tribord PORT_NAME_MAP ""
set_interface_property BP_Tribord CMSIS_SVD_VARIABLES ""
set_interface_property BP_Tribord SVD_ADDRESS_GROUP ""

add_interface_port BP_Tribord BP_Tribord beginbursttransfer Input 1


# 
# connection point lesBabord
# 
add_interface lesBabord conduit end
set_interface_property lesBabord associatedClock clock
set_interface_property lesBabord associatedReset ""
set_interface_property lesBabord ENABLED true
set_interface_property lesBabord EXPORT_OF ""
set_interface_property lesBabord PORT_NAME_MAP ""
set_interface_property lesBabord CMSIS_SVD_VARIABLES ""
set_interface_property lesBabord SVD_ADDRESS_GROUP ""

add_interface_port lesBabord ledBabord writeresponsevalid_n Output 1


# 
# connection point ledSTBY
# 
add_interface ledSTBY conduit end
set_interface_property ledSTBY associatedClock clock
set_interface_property ledSTBY associatedReset ""
set_interface_property ledSTBY ENABLED true
set_interface_property ledSTBY EXPORT_OF ""
set_interface_property ledSTBY PORT_NAME_MAP ""
set_interface_property ledSTBY CMSIS_SVD_VARIABLES ""
set_interface_property ledSTBY SVD_ADDRESS_GROUP ""

add_interface_port ledSTBY ledSTBY writeresponsevalid_n Output 1


# 
# connection point ledTribord
# 
add_interface ledTribord conduit end
set_interface_property ledTribord associatedClock clock
set_interface_property ledTribord associatedReset ""
set_interface_property ledTribord ENABLED true
set_interface_property ledTribord EXPORT_OF ""
set_interface_property ledTribord PORT_NAME_MAP ""
set_interface_property ledTribord CMSIS_SVD_VARIABLES ""
set_interface_property ledTribord SVD_ADDRESS_GROUP ""

add_interface_port ledTribord ledTribord writeresponsevalid_n Output 1

